### ISSUE TITLE
Replace STM32CubeIDE project with CMake

### ISSUE THREAD

**Issue by r0x57n** [LiU-SeeGoals/basestation#2]
See ... when it's merged we could start looking at this.

**Comment by r0x57n** [comment]
https://github.com/ObKo/stm32-cmake/pull/320#issuecomment-1874402690

**Comment by r0x57n** [comment]
we can't use the stm32-cmake since it doesn't include support for Azure RTOS currently, see issue 236 in the above linked repo

**Comment by Paladinking** [comment]
We now have working CMakeLists.txt for both robot and basestation.
